[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000233D7BAB610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db34f83ed018d1f79d26b5f5b7d92989
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000233D7BAB890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db34f83ed018d1f79d26b5f5b7d92989
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000233D7BF8640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db34f83ed018d1f79d26b5f5b7d92989